vich_uploader:
    db_driver: orm

    mappings:
        watches:
            uri_prefix: /images/watches
            upload_destination: '%kernel.project_dir%/public/images/watches'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
